version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      timezone: "Europe/Paris"
    commit-message:
      prefix: "[github-action] "
    assignees:
      - "IliyanKostov9"
    reviewers:
      - "IliyanKostov9"
