---
owners:
  - name: IliyanKostov9
    enable_on_org_level: false
    repos:
      - name: nixos-config
        secrets:
          enable: true
          variables:
            - GIT_AUTO_MERGE
            - GITGUARDIAN_API_KEY
            - GIT_USERNAME
            - GIT_PASSWORD
            - CACHIX_AUTH_TOKEN

      - name: nixos-wsl
        secrets:
          enable: true
          variables:
            - GITGUARDIAN_API_KEY

      - name: nvim-config
        secrets:
          enable: true
          variables:
            - GIT_AUTO_MERGE
            - GITGUARDIAN_API_KEY
            - GIT_USERNAME
            - GIT_PASSWORD
            - CACHIX_AUTH_TOKEN

      - name: .dotfiles
        secrets:
          enable: false

      - name: portfolio
        secrets:
          enable: true
          variables:
            - GIT_AUTO_MERGE
            - GITGUARDIAN_API_KEY
            - SONAR_TOKEN
            - CACHIX_AUTH_TOKEN
            - PORTFOLIO_S3_AWS_KEY_ID
            - PORTFOLIO_S3_AWS_SECRET_ACCESS_KEY
            - PORTFOLIO_S3_AWS_BUCKET

      - name: flake-templates
        secrets:
          enable: true
          variables:
            - GIT_AUTO_MERGE
            - GITGUARDIAN_API_KEY
            - GIT_USERNAME
            - GIT_PASSWORD
            - CACHIX_AUTH_TOKEN
            - GIT_PR_PUSH_UPDATES_CI

  - name: Tu-Varna-2019
    enable_on_org_level: false

  - name: ZProfile
    enable_on_org_level: false
    repos:
      - name: flutter-client
        secrets:
          enable: true
          variables:
            - GIT_AUTO_MERGE
            - GITGUARDIAN_API_KEY
            - SONAR_TOKEN
            - CACHIX_AUTH_TOKEN
