---
owners:
  - name: IliyanKostov9
    org: false
    repos:
      - name: nixos-config
        secrets:
          enable: true
          variables:
            - GIT_AUTO_MERGE
            - GITGUARDIAN_API_KEY
            - GIT_USERNAME
            - GIT_PASSWORD

      - name: nixos-wsl
        secrets:
          enable: true
          variables:
            - GITGUARDIAN_API_KEY

      - name: nvim-config
        secrets:
          enable: true
          variables:
            - GIT_AUTO_MERGE
            - GITGUARDIAN_API_KEY
            - GIT_USERNAME
            - GIT_PASSWORD

      - name: .dotfiles
        secrets:
          enable: true

      - name: portfolio
        secrets:
          enable: true
          variables:
            - GIT_AUTO_MERGE
            - GITGUARDIAN_API_KEY
            - SONAR_TOKEN

      - name: flake-templates
        secrets:
          enable: true
          variables:
            - GIT_AUTO_MERGE
            - GITGUARDIAN_API_KEY
            - GIT_USERNAME
            - GIT_PASSWORD

  - name: Tu-Varna-2019
    org: true

  - name: ZProfile
    org: true
