name: Semantic release
on:
  workflow_dispatch:
    inputs:
      owner:
        description: The owner to release
        required: true
        type: choice
        options:
          - IliyanKostov9
          - Tu-Varna-2019
          - ZProfile
      repo:
        description: The repository to release
        required: true
        type: string
      version:
        description: The version number to release
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    name: Perform release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout & create an artifact
        run: |
          gh repo clone $OWNER_REPO workspace/$REPO
          zip -r workspace/$REPO/$REPO.zip workspace/$REPO
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          OWNER_REPO: ${{ inputs.owner }}/${{ inputs.repo }}
          REPO: ${{ inputs.repo }}

      - name: Semantic Release
        run: |
          cd "workspace/$REPO"
          git fetch --tags
          version=$(git tag -l --sort=-version:refname | head -n 1)
          declare -A sem_version_index_mapping=( ["major"]=0 ["minor"]=1 ["patch"]=2 )

          if [[ $version != "" ]]; then
            echo "Found the latest version is: $version"

            IFS=". " read -r -a array <<< "${version#v}"
            index=${sem_version_index_mapping[$VERSION_TYPE]}
            echo "$((array[$index]++))"
            VERSION="v$( IFS=$". "; echo "${array[*]}")"

            echo "Version bumped: $VERSION"

          else
            VERSION="v1.0.0"
            echo "Couldn't find version in repository $REPO. Creating a new fresh version: $VERSION"
          fi

          gh release create $VERSION --generate-notes "$REPO.zip#$VERSION"

        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: ${{ inputs.repo }}
          VERSION_TYPE: ${{ inputs.version }}

      - name: Create a release branch
        run: |
          cd "workspace/$REPO"
          RELEASE_BRANCH=release/v$VERSION

          git config --global user.name "landing-zone"
          git config --global user.email "landing-zone@noreply.github.com"
          git checkout -b $RELEASE_BRANCH
          git remote set-url origin https://x-access-token:${GIT_PUSH}@github.com/${OWNER_REPO}.git
          git push -u origin $RELEASE_BRANCH
        env:
          GIT_PUSH: ${{ secrets.GIT_PUSH }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: ${{ inputs.repo }}
          OWNER_REPO: ${{ inputs.owner }}/${{ inputs.repo }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
